//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLauncher2._0 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseVsyncS {
            get {
                return ((bool)(this["UseVsyncS"]));
            }
            set {
                this["UseVsyncS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VideoQualityS {
            get {
                return ((int)(this["VideoQualityS"]));
            }
            set {
                this["VideoQualityS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ResSelectedIndexS {
            get {
                return ((int)(this["ResSelectedIndexS"]));
            }
            set {
                this["ResSelectedIndexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DisplaySelectedIndexS {
            get {
                return ((int)(this["DisplaySelectedIndexS"]));
            }
            set {
                this["DisplaySelectedIndexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnisSelectedIndexS {
            get {
                return ((int)(this["AnisSelectedIndexS"]));
            }
            set {
                this["AnisSelectedIndexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothFrameS {
            get {
                return ((bool)(this["SmoothFrameS"]));
            }
            set {
                this["SmoothFrameS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StaticDecalsS {
            get {
                return ((bool)(this["StaticDecalsS"]));
            }
            set {
                this["StaticDecalsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamicShS {
            get {
                return ((bool)(this["DynamicShS"]));
            }
            set {
                this["DynamicShS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LightEnviroS {
            get {
                return ((bool)(this["LightEnviroS"]));
            }
            set {
                this["LightEnviroS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlobS {
            get {
                return ((bool)(this["BlobS"]));
            }
            set {
                this["BlobS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AmbientS {
            get {
                return ((bool)(this["AmbientS"]));
            }
            set {
                this["AmbientS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BloomS {
            get {
                return ((bool)(this["BloomS"]));
            }
            set {
                this["BloomS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DistortionS {
            get {
                return ((bool)(this["DistortionS"]));
            }
            set {
                this["DistortionS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrilinearS {
            get {
                return ((bool)(this["TrilinearS"]));
            }
            set {
                this["TrilinearS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hudS {
            get {
                return ((bool)(this["hudS"]));
            }
            set {
                this["hudS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenderS {
            get {
                return ((bool)(this["RenderS"]));
            }
            set {
                this["RenderS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamicDecals {
            get {
                return ((bool)(this["DynamicDecals"]));
            }
            set {
                this["DynamicDecals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LevelPariclesS {
            get {
                return ((bool)(this["LevelPariclesS"]));
            }
            set {
                this["LevelPariclesS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DynamicLightsS {
            get {
                return ((bool)(this["DynamicLightsS"]));
            }
            set {
                this["DynamicLightsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DepthOfFieldS {
            get {
                return ((bool)(this["DepthOfFieldS"]));
            }
            set {
                this["DepthOfFieldS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompositeDynamicLightsS {
            get {
                return ((bool)(this["CompositeDynamicLightsS"]));
            }
            set {
                this["CompositeDynamicLightsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DirectionalLightmapsS {
            get {
                return ((bool)(this["DirectionalLightmapsS"]));
            }
            set {
                this["DirectionalLightmapsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MotionBlurS {
            get {
                return ((bool)(this["MotionBlurS"]));
            }
            set {
                this["MotionBlurS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QualityBloomS {
            get {
                return ((bool)(this["QualityBloomS"]));
            }
            set {
                this["QualityBloomS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DropParticleDistortionS {
            get {
                return ((bool)(this["DropParticleDistortionS"]));
            }
            set {
                this["DropParticleDistortionS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpeedTreeLeavesS {
            get {
                return ((bool)(this["SpeedTreeLeavesS"]));
            }
            set {
                this["SpeedTreeLeavesS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpeedTreeFrondsS {
            get {
                return ((bool)(this["SpeedTreeFrondsS"]));
            }
            set {
                this["SpeedTreeFrondsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnlyStreamInTexturesS {
            get {
                return ((bool)(this["OnlyStreamInTexturesS"]));
            }
            set {
                this["OnlyStreamInTexturesS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LensFlaresS {
            get {
                return ((bool)(this["LensFlaresS"]));
            }
            set {
                this["LensFlaresS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FogVolumesS {
            get {
                return ((bool)(this["FogVolumesS"]));
            }
            set {
                this["FogVolumesS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FloatingPointRenderS {
            get {
                return ((bool)(this["FloatingPointRenderS"]));
            }
            set {
                this["FloatingPointRenderS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OneFrameThreadLagS {
            get {
                return ((bool)(this["OneFrameThreadLagS"]));
            }
            set {
                this["OneFrameThreadLagS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpscaleScreenPercS {
            get {
                return ((bool)(this["UpscaleScreenPercS"]));
            }
            set {
                this["UpscaleScreenPercS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableHighPolyS {
            get {
                return ((bool)(this["EnableHighPolyS"]));
            }
            set {
                this["EnableHighPolyS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VSMShadowsS {
            get {
                return ((bool)(this["VSMShadowsS"]));
            }
            set {
                this["VSMShadowsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BranchingPCFS {
            get {
                return ((bool)(this["BranchingPCFS"]));
            }
            set {
                this["BranchingPCFS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BetterModulatedShadowsS {
            get {
                return ((bool)(this["BetterModulatedShadowsS"]));
            }
            set {
                this["BetterModulatedShadowsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForegroundShadowsS {
            get {
                return ((bool)(this["ForegroundShadowsS"]));
            }
            set {
                this["ForegroundShadowsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimplifiedVehicleMaterialsS {
            get {
                return ((bool)(this["SimplifiedVehicleMaterialsS"]));
            }
            set {
                this["SimplifiedVehicleMaterialsS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompressLocalCharacterS {
            get {
                return ((bool)(this["CompressLocalCharacterS"]));
            }
            set {
                this["CompressLocalCharacterS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompressLocalVehicleS {
            get {
                return ((bool)(this["CompressLocalVehicleS"]));
            }
            set {
                this["CompressLocalVehicleS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompressOtherCharacterS {
            get {
                return ((bool)(this["CompressOtherCharacterS"]));
            }
            set {
                this["CompressOtherCharacterS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompressOtherVehicleS {
            get {
                return ((bool)(this["CompressOtherVehicleS"]));
            }
            set {
                this["CompressOtherVehicleS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompressNormalS {
            get {
                return ((bool)(this["CompressNormalS"]));
            }
            set {
                this["CompressNormalS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int VehicleTexS {
            get {
                return ((int)(this["VehicleTexS"]));
            }
            set {
                this["VehicleTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PedestrianTexS {
            get {
                return ((int)(this["PedestrianTexS"]));
            }
            set {
                this["PedestrianTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CityVehicleTexS {
            get {
                return ((int)(this["CityVehicleTexS"]));
            }
            set {
                this["CityVehicleTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ItemWeaponTexS {
            get {
                return ((int)(this["ItemWeaponTexS"]));
            }
            set {
                this["ItemWeaponTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PrimitiveTexS {
            get {
                return ((int)(this["PrimitiveTexS"]));
            }
            set {
                this["PrimitiveTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UITexS {
            get {
                return ((int)(this["UITexS"]));
            }
            set {
                this["UITexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShadowResTexS {
            get {
                return ((int)(this["ShadowResTexS"]));
            }
            set {
                this["ShadowResTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VFXTexS {
            get {
                return ((int)(this["VFXTexS"]));
            }
            set {
                this["VFXTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LightShadowMapTexS {
            get {
                return ((int)(this["LightShadowMapTexS"]));
            }
            set {
                this["LightShadowMapTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RenderTexS {
            get {
                return ((int)(this["RenderTexS"]));
            }
            set {
                this["RenderTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SignageTexS {
            get {
                return ((int)(this["SignageTexS"]));
            }
            set {
                this["SignageTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MissionGraffitiTexS {
            get {
                return ((int)(this["MissionGraffitiTexS"]));
            }
            set {
                this["MissionGraffitiTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlayerStatueTexS {
            get {
                return ((int)(this["PlayerStatueTexS"]));
            }
            set {
                this["PlayerStatueTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SharedCharacterTexS {
            get {
                return ((int)(this["SharedCharacterTexS"]));
            }
            set {
                this["SharedCharacterTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SharedVehicleTexS {
            get {
                return ((int)(this["SharedVehicleTexS"]));
            }
            set {
                this["SharedVehicleTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ContactTexS {
            get {
                return ((int)(this["ContactTexS"]));
            }
            set {
                this["ContactTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CharacterDNTexS {
            get {
                return ((int)(this["CharacterDNTexS"]));
            }
            set {
                this["CharacterDNTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PlayerVehicleTexS {
            get {
                return ((int)(this["PlayerVehicleTexS"]));
            }
            set {
                this["PlayerVehicleTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CharacterTexS {
            get {
                return ((int)(this["CharacterTexS"]));
            }
            set {
                this["CharacterTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PropTexS {
            get {
                return ((int)(this["PropTexS"]));
            }
            set {
                this["PropTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int EnvironmentTexS {
            get {
                return ((int)(this["EnvironmentTexS"]));
            }
            set {
                this["EnvironmentTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int UnknownTexS {
            get {
                return ((int)(this["UnknownTexS"]));
            }
            set {
                this["UnknownTexS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string VehicleTextS {
            get {
                return ((string)(this["VehicleTextS"]));
            }
            set {
                this["VehicleTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string UnknownTextS {
            get {
                return ((string)(this["UnknownTextS"]));
            }
            set {
                this["UnknownTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string EnvironmentTextS {
            get {
                return ((string)(this["EnvironmentTextS"]));
            }
            set {
                this["EnvironmentTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string PropTextS {
            get {
                return ((string)(this["PropTextS"]));
            }
            set {
                this["PropTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public string CharacterTextS {
            get {
                return ((string)(this["CharacterTextS"]));
            }
            set {
                this["CharacterTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string PedestrianTextS {
            get {
                return ((string)(this["PedestrianTextS"]));
            }
            set {
                this["PedestrianTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string CityVehicleTextS {
            get {
                return ((string)(this["CityVehicleTextS"]));
            }
            set {
                this["CityVehicleTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string ItemWeaponTextS {
            get {
                return ((string)(this["ItemWeaponTextS"]));
            }
            set {
                this["ItemWeaponTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string PrimitiveTextS {
            get {
                return ((string)(this["PrimitiveTextS"]));
            }
            set {
                this["PrimitiveTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public string UITextS {
            get {
                return ((string)(this["UITextS"]));
            }
            set {
                this["UITextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string ShadowTextS {
            get {
                return ((string)(this["ShadowTextS"]));
            }
            set {
                this["ShadowTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public string VFXTextS {
            get {
                return ((string)(this["VFXTextS"]));
            }
            set {
                this["VFXTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string LightShadowTextS {
            get {
                return ((string)(this["LightShadowTextS"]));
            }
            set {
                this["LightShadowTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public string RenderTextS {
            get {
                return ((string)(this["RenderTextS"]));
            }
            set {
                this["RenderTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string SignageTextS {
            get {
                return ((string)(this["SignageTextS"]));
            }
            set {
                this["SignageTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string MissionGraffitiTextS {
            get {
                return ((string)(this["MissionGraffitiTextS"]));
            }
            set {
                this["MissionGraffitiTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string PlayerStatueTextS {
            get {
                return ((string)(this["PlayerStatueTextS"]));
            }
            set {
                this["PlayerStatueTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string SharedCharacterTextS {
            get {
                return ((string)(this["SharedCharacterTextS"]));
            }
            set {
                this["SharedCharacterTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string SharedVehicleTextS {
            get {
                return ((string)(this["SharedVehicleTextS"]));
            }
            set {
                this["SharedVehicleTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public string ContactTextS {
            get {
                return ((string)(this["ContactTextS"]));
            }
            set {
                this["ContactTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string CharacterDNTextS {
            get {
                return ((string)(this["CharacterDNTextS"]));
            }
            set {
                this["CharacterDNTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Low Quality")]
        public string PlayerVehicleTextS {
            get {
                return ((string)(this["PlayerVehicleTextS"]));
            }
            set {
                this["PlayerVehicleTextS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int LanguageSelectorSetting {
            get {
                return ((int)(this["LanguageSelectorSetting"]));
            }
            set {
                this["LanguageSelectorSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoMoviesSetting {
            get {
                return ((bool)(this["NoMoviesSetting"]));
            }
            set {
                this["NoMoviesSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdate {
            get {
                return ((bool)(this["AutoUpdate"]));
            }
            set {
                this["AutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DynamicBG {
            get {
                return ((bool)(this["DynamicBG"]));
            }
            set {
                this["DynamicBG"] = value;
            }
        }
    }
}
